In [0]:
import numpy as np

#Sigmoid(x) = 1/(1+e^(-x))

In [0]:
def sigmoid(x): 
    return 1/(1+np.exp(-x))

#d/dx(Sigmoid(x)) = x(1-x)

In [0]:
def sigmoid_derivative(x):  
    return x*(1-x)  

### **Making a simple dataset**

#inputs

In [0]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

#outputs required

In [0]:
training_outputs = np.array([[0,1,1,0]]).T  

#Defining synaptics weights

In [0]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3,1)) - 1

#synaptic weights before training

In [40]:
print("Random starting synaptic weights: ")
print(synaptic_weights)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


#For training the machine on weightage and the output will be closer as the no. of iterations increases

In [0]:
for iteration in range(100000):
    input_layer = training_inputs
    output = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - output
    adjusment = error * sigmoid_derivative(output)
    synaptic_weights += np.dot(input_layer.T, adjusment)

#Synaptic weights after training

In [42]:
print('Synaptic Weights after training')
print(synaptic_weights)    

Synaptic Weights after training
[[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]


#predicted outputs

In [43]:
print('Output after training: ')    
print(output)

Output after training: 
[[0.00301758]
 [0.99753723]
 [0.99799161]
 [0.00246109]]
